// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/password-manager/password-manager.proto

package go_micro_api_password_manager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PasswordEntry struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Date                 int64    `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Deleted              bool     `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordEntry) Reset()         { *m = PasswordEntry{} }
func (m *PasswordEntry) String() string { return proto.CompactTextString(m) }
func (*PasswordEntry) ProtoMessage()    {}
func (*PasswordEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e506bb32f7b691, []int{0}
}

func (m *PasswordEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordEntry.Unmarshal(m, b)
}
func (m *PasswordEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordEntry.Marshal(b, m, deterministic)
}
func (m *PasswordEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordEntry.Merge(m, src)
}
func (m *PasswordEntry) XXX_Size() int {
	return xxx_messageInfo_PasswordEntry.Size(m)
}
func (m *PasswordEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordEntry proto.InternalMessageInfo

func (m *PasswordEntry) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *PasswordEntry) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PasswordEntry) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PasswordEntry) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *PasswordEntry) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type UpdatePasswordRequest struct {
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Date                 int64    `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	Deleted              bool     `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e506bb32f7b691, []int{1}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *UpdatePasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePasswordRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *UpdatePasswordRequest) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type ListPasswordRequest struct {
	Date                 int64    `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPasswordRequest) Reset()         { *m = ListPasswordRequest{} }
func (m *ListPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ListPasswordRequest) ProtoMessage()    {}
func (*ListPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e506bb32f7b691, []int{2}
}

func (m *ListPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPasswordRequest.Unmarshal(m, b)
}
func (m *ListPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ListPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPasswordRequest.Merge(m, src)
}
func (m *ListPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ListPasswordRequest.Size(m)
}
func (m *ListPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPasswordRequest proto.InternalMessageInfo

func (m *ListPasswordRequest) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type ListPasswordResponse struct {
	Passwords            []*PasswordEntry `protobuf:"bytes,1,rep,name=passwords,proto3" json:"passwords,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPasswordResponse) Reset()         { *m = ListPasswordResponse{} }
func (m *ListPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ListPasswordResponse) ProtoMessage()    {}
func (*ListPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e506bb32f7b691, []int{3}
}

func (m *ListPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPasswordResponse.Unmarshal(m, b)
}
func (m *ListPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ListPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPasswordResponse.Merge(m, src)
}
func (m *ListPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ListPasswordResponse.Size(m)
}
func (m *ListPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPasswordResponse proto.InternalMessageInfo

func (m *ListPasswordResponse) GetPasswords() []*PasswordEntry {
	if m != nil {
		return m.Passwords
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_73e506bb32f7b691, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PasswordEntry)(nil), "go.micro.api.password_manager.PasswordEntry")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "go.micro.api.password_manager.UpdatePasswordRequest")
	proto.RegisterType((*ListPasswordRequest)(nil), "go.micro.api.password_manager.ListPasswordRequest")
	proto.RegisterType((*ListPasswordResponse)(nil), "go.micro.api.password_manager.ListPasswordResponse")
	proto.RegisterType((*Empty)(nil), "go.micro.api.password_manager.Empty")
}

func init() {
	proto.RegisterFile("proto/password-manager/password-manager.proto", fileDescriptor_73e506bb32f7b691)
}

var fileDescriptor_73e506bb32f7b691 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x97, 0x75, 0x7f, 0x8f, 0x4c, 0x21, 0xfe, 0x21, 0x0c, 0x84, 0x12, 0xbc, 0xa8, 0xe0,
	0x22, 0x6c, 0xbe, 0xc2, 0x6e, 0x44, 0x41, 0x0a, 0x5e, 0x4b, 0x66, 0xc3, 0x28, 0xd8, 0x24, 0x26,
	0x19, 0x32, 0xdf, 0xc1, 0x4b, 0x1f, 0x57, 0x90, 0x75, 0x8d, 0x5b, 0xb5, 0x5b, 0xf1, 0xae, 0x27,
	0xe7, 0xfb, 0x4e, 0x7e, 0xfd, 0x4e, 0x60, 0xa4, 0x8d, 0x72, 0xea, 0x5a, 0x73, 0x6b, 0xdf, 0x94,
	0x49, 0x46, 0x19, 0x97, 0x7c, 0x2e, 0xcc, 0x9f, 0x03, 0x96, 0xeb, 0xf0, 0xf9, 0x5c, 0xb1, 0x2c,
	0x7d, 0x36, 0x8a, 0x71, 0x9d, 0x32, 0x2f, 0x7a, 0x2a, 0x44, 0xf4, 0x03, 0xc1, 0xe0, 0xa1, 0x38,
	0x9c, 0x4a, 0x67, 0x96, 0xf8, 0x0c, 0x3a, 0x89, 0xca, 0x78, 0x2a, 0x09, 0x0a, 0x51, 0xd4, 0x8f,
	0x8b, 0x0a, 0x0f, 0xa1, 0xb7, 0xb0, 0xc2, 0x48, 0x9e, 0x09, 0xd2, 0xcc, 0x3b, 0x3f, 0xf5, 0xaa,
	0xe7, 0x27, 0x93, 0x60, 0xdd, 0xf3, 0x35, 0xc6, 0xd0, 0x4a, 0xb8, 0x13, 0xa4, 0x15, 0xa2, 0x28,
	0x88, 0xf3, 0x6f, 0x4c, 0xa0, 0x9b, 0x88, 0x17, 0xe1, 0x44, 0x42, 0xda, 0x21, 0x8a, 0x7a, 0xb1,
	0x2f, 0xe9, 0x27, 0x82, 0xd3, 0x47, 0xbd, 0x12, 0x79, 0xaa, 0x58, 0xbc, 0x2e, 0x84, 0x75, 0x5b,
	0x5c, 0xcd, 0x9d, 0x5c, 0xc1, 0x1e, 0xae, 0xd6, 0x0e, 0xae, 0x76, 0x35, 0x57, 0xa7, 0xcc, 0x75,
	0x09, 0xc7, 0x77, 0xa9, 0x75, 0xbf, 0xa1, 0xfc, 0x10, 0xb4, 0x19, 0x42, 0x67, 0x70, 0x52, 0x96,
	0x5a, 0xad, 0xa4, 0x15, 0xf8, 0x16, 0xfa, 0xfe, 0x72, 0x4b, 0x50, 0x18, 0x44, 0x07, 0xe3, 0x2b,
	0xb6, 0x77, 0x3b, 0xac, 0xb4, 0x99, 0x78, 0x63, 0xa7, 0x5d, 0x68, 0x4f, 0x33, 0xed, 0x96, 0xe3,
	0x2f, 0x04, 0x47, 0x5e, 0x75, 0xbf, 0x76, 0x61, 0x09, 0x87, 0xe5, 0x08, 0xf1, 0x4d, 0xcd, 0x3d,
	0x95, 0x89, 0x0f, 0x2f, 0x6a, 0x5c, 0x39, 0x01, 0x6d, 0xe0, 0x77, 0x18, 0x6c, 0xff, 0xb0, 0xc5,
	0xe3, 0x1a, 0x63, 0x45, 0x92, 0xc3, 0xc9, 0xbf, 0x3c, 0xeb, 0x48, 0x69, 0x63, 0xd6, 0xc9, 0x5f,
	0xf9, 0xe4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x01, 0x88, 0xf8, 0xee, 0x16, 0x03, 0x00, 0x00,
}
