// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	RegisterUser(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*Empty, error)
	GetVerifier(ctx context.Context, in *VerifierRequest, opts ...client.CallOption) (*VerifierResponse, error)
	AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...client.CallOption) (*Empty, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) RegisterUser(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.RegisterUser", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetVerifier(ctx context.Context, in *VerifierRequest, opts ...client.CallOption) (*VerifierResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetVerifier", in)
	out := new(VerifierResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...client.CallOption) (*Empty, error) {
	req := c.c.NewRequest(c.name, "UserService.AddDevice", in)
	out := new(Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	RegisterUser(context.Context, *RegisterRequest, *Empty) error
	GetVerifier(context.Context, *VerifierRequest, *VerifierResponse) error
	AddDevice(context.Context, *AddDeviceRequest, *Empty) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		RegisterUser(ctx context.Context, in *RegisterRequest, out *Empty) error
		GetVerifier(ctx context.Context, in *VerifierRequest, out *VerifierResponse) error
		AddDevice(ctx context.Context, in *AddDeviceRequest, out *Empty) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) RegisterUser(ctx context.Context, in *RegisterRequest, out *Empty) error {
	return h.UserServiceHandler.RegisterUser(ctx, in, out)
}

func (h *userServiceHandler) GetVerifier(ctx context.Context, in *VerifierRequest, out *VerifierResponse) error {
	return h.UserServiceHandler.GetVerifier(ctx, in, out)
}

func (h *userServiceHandler) AddDevice(ctx context.Context, in *AddDeviceRequest, out *Empty) error {
	return h.UserServiceHandler.AddDevice(ctx, in, out)
}
