// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Salt                 []byte   `protobuf:"bytes,5,opt,name=Salt,proto3" json:"Salt,omitempty"`
	Verifier             []byte   `protobuf:"bytes,6,opt,name=Verifier,proto3" json:"Verifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *RegisterRequest) GetVerifier() []byte {
	if m != nil {
		return m.Verifier
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type VerifierRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=Device,proto3" json:"Device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifierRequest) Reset()         { *m = VerifierRequest{} }
func (m *VerifierRequest) String() string { return proto.CompactTextString(m) }
func (*VerifierRequest) ProtoMessage()    {}
func (*VerifierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *VerifierRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierRequest.Unmarshal(m, b)
}
func (m *VerifierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierRequest.Marshal(b, m, deterministic)
}
func (m *VerifierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierRequest.Merge(m, src)
}
func (m *VerifierRequest) XXX_Size() int {
	return xxx_messageInfo_VerifierRequest.Size(m)
}
func (m *VerifierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierRequest proto.InternalMessageInfo

func (m *VerifierRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifierRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type VerifierResponse struct {
	Verifier             []byte   `protobuf:"bytes,1,opt,name=Verifier,proto3" json:"Verifier,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=Salt,proto3" json:"Salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifierResponse) Reset()         { *m = VerifierResponse{} }
func (m *VerifierResponse) String() string { return proto.CompactTextString(m) }
func (*VerifierResponse) ProtoMessage()    {}
func (*VerifierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *VerifierResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierResponse.Unmarshal(m, b)
}
func (m *VerifierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierResponse.Marshal(b, m, deterministic)
}
func (m *VerifierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierResponse.Merge(m, src)
}
func (m *VerifierResponse) XXX_Size() int {
	return xxx_messageInfo_VerifierResponse.Size(m)
}
func (m *VerifierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierResponse proto.InternalMessageInfo

func (m *VerifierResponse) GetVerifier() []byte {
	if m != nil {
		return m.Verifier
	}
	return nil
}

func (m *VerifierResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type AddDeviceRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=Device,proto3" json:"Device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceRequest) Reset()         { *m = AddDeviceRequest{} }
func (m *AddDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*AddDeviceRequest) ProtoMessage()    {}
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *AddDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceRequest.Unmarshal(m, b)
}
func (m *AddDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceRequest.Marshal(b, m, deterministic)
}
func (m *AddDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceRequest.Merge(m, src)
}
func (m *AddDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_AddDeviceRequest.Size(m)
}
func (m *AddDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceRequest proto.InternalMessageInfo

func (m *AddDeviceRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddDeviceRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*Empty)(nil), "user.Empty")
	proto.RegisterType((*VerifierRequest)(nil), "user.VerifierRequest")
	proto.RegisterType((*VerifierResponse)(nil), "user.VerifierResponse")
	proto.RegisterType((*AddDeviceRequest)(nil), "user.AddDeviceRequest")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x5e, 0xe6, 0x56, 0xed, 0xeb, 0x60, 0xe3, 0xe1, 0x46, 0x29, 0x1e, 0x46, 0x4e, 0x3b, 0x4d,
	0x98, 0x9e, 0x05, 0xc5, 0xcd, 0x8b, 0xa7, 0x0e, 0xbd, 0x57, 0xf7, 0x94, 0xc0, 0xb6, 0xd6, 0x24,
	0x13, 0xfc, 0x51, 0x9e, 0xfd, 0x7b, 0x92, 0xa4, 0x4d, 0x59, 0x4e, 0x82, 0x97, 0x92, 0xef, 0xfb,
	0xf2, 0xbe, 0xf7, 0xbd, 0xbc, 0xc2, 0xb8, 0x92, 0xa5, 0x2e, 0x2f, 0x0f, 0x8a, 0xa4, 0xfd, 0xcc,
	0x2d, 0xc6, 0x9e, 0x39, 0xf3, 0x6f, 0x06, 0xc3, 0x9c, 0xde, 0x85, 0xd2, 0x24, 0x73, 0xfa, 0x38,
	0x90, 0xd2, 0x98, 0xc1, 0xd9, 0x93, 0x22, 0xb9, 0x2f, 0x76, 0x94, 0xb2, 0x29, 0x9b, 0xc5, 0xb9,
	0xc7, 0x78, 0x01, 0xf1, 0x4a, 0x48, 0xa5, 0xad, 0xd8, 0xb5, 0x62, 0x4b, 0x98, 0xca, 0xc7, 0xa2,
	0x16, 0x4f, 0x5c, 0x65, 0x83, 0xf1, 0x1c, 0xfa, 0xcb, 0x5d, 0x21, 0xb6, 0x69, 0xcf, 0x0a, 0x0e,
	0x20, 0x42, 0x6f, 0x5d, 0x6c, 0x75, 0xda, 0x9f, 0xb2, 0xd9, 0x20, 0xb7, 0x67, 0xe3, 0xf2, 0x4c,
	0x52, 0xbc, 0x09, 0x92, 0x69, 0x64, 0x79, 0x8f, 0xf9, 0xa9, 0x71, 0xa9, 0xf4, 0x17, 0x5f, 0xc2,
	0xb0, 0x21, 0xff, 0x92, 0x7b, 0x02, 0xd1, 0x3d, 0x7d, 0x8a, 0xd7, 0x26, 0x74, 0x8d, 0xf8, 0x1d,
	0x8c, 0x5a, 0x1b, 0x55, 0x95, 0x7b, 0x45, 0x47, 0xfd, 0xd9, 0x71, 0x7f, 0x9f, 0xb7, 0xdb, 0xe6,
	0xe5, 0x2b, 0x18, 0xdd, 0x6e, 0x36, 0xce, 0xf0, 0x1f, 0x59, 0x16, 0x3f, 0x0c, 0x12, 0x73, 0x69,
	0x4d, 0xd2, 0x60, 0xbc, 0x86, 0x41, 0xb3, 0x1a, 0x43, 0xe3, 0x78, 0x6e, 0xd7, 0x17, 0xac, 0x2b,
	0x4b, 0x1c, 0xed, 0x9e, 0xa5, 0x83, 0x37, 0x90, 0x3c, 0x90, 0xf6, 0x81, 0xeb, 0xa2, 0xe0, 0xad,
	0xb2, 0x49, 0x48, 0xbb, 0xd9, 0x79, 0x07, 0x17, 0x10, 0xfb, 0x69, 0xb0, 0xbe, 0x16, 0x8e, 0x17,
	0xf4, 0x7c, 0x89, 0xec, 0x2f, 0x75, 0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x8f, 0x9e, 0xcc,
	0x6b, 0x02, 0x00, 0x00,
}
