// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_api_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Device               string   `protobuf:"bytes,5,opt,name=Device,proto3" json:"Device,omitempty"`
	SRPSalt              []byte   `protobuf:"bytes,6,opt,name=SRPSalt,proto3" json:"SRPSalt,omitempty"`
	SRPVerifier          []byte   `protobuf:"bytes,7,opt,name=SRPVerifier,proto3" json:"SRPVerifier,omitempty"`
	MUKSalt              []byte   `protobuf:"bytes,8,opt,name=MUKSalt,proto3" json:"MUKSalt,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,9,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	EncPrivateKey        []byte   `protobuf:"bytes,10,opt,name=EncPrivateKey,proto3" json:"EncPrivateKey,omitempty"`
	EncVaultKey          []byte   `protobuf:"bytes,11,opt,name=EncVaultKey,proto3" json:"EncVaultKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *RegisterRequest) GetSRPSalt() []byte {
	if m != nil {
		return m.SRPSalt
	}
	return nil
}

func (m *RegisterRequest) GetSRPVerifier() []byte {
	if m != nil {
		return m.SRPVerifier
	}
	return nil
}

func (m *RegisterRequest) GetMUKSalt() []byte {
	if m != nil {
		return m.MUKSalt
	}
	return nil
}

func (m *RegisterRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *RegisterRequest) GetEncPrivateKey() []byte {
	if m != nil {
		return m.EncPrivateKey
	}
	return nil
}

func (m *RegisterRequest) GetEncVaultKey() []byte {
	if m != nil {
		return m.EncVaultKey
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type VerifierRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Device               string   `protobuf:"bytes,2,opt,name=Device,proto3" json:"Device,omitempty"`
	AccessKey            string   `protobuf:"bytes,3,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifierRequest) Reset()         { *m = VerifierRequest{} }
func (m *VerifierRequest) String() string { return proto.CompactTextString(m) }
func (*VerifierRequest) ProtoMessage()    {}
func (*VerifierRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *VerifierRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierRequest.Unmarshal(m, b)
}
func (m *VerifierRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierRequest.Marshal(b, m, deterministic)
}
func (m *VerifierRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierRequest.Merge(m, src)
}
func (m *VerifierRequest) XXX_Size() int {
	return xxx_messageInfo_VerifierRequest.Size(m)
}
func (m *VerifierRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierRequest proto.InternalMessageInfo

func (m *VerifierRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifierRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *VerifierRequest) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

type VerifierResponse struct {
	Verifier             []byte   `protobuf:"bytes,1,opt,name=Verifier,proto3" json:"Verifier,omitempty"`
	Salt                 []byte   `protobuf:"bytes,2,opt,name=Salt,proto3" json:"Salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifierResponse) Reset()         { *m = VerifierResponse{} }
func (m *VerifierResponse) String() string { return proto.CompactTextString(m) }
func (*VerifierResponse) ProtoMessage()    {}
func (*VerifierResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *VerifierResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierResponse.Unmarshal(m, b)
}
func (m *VerifierResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierResponse.Marshal(b, m, deterministic)
}
func (m *VerifierResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierResponse.Merge(m, src)
}
func (m *VerifierResponse) XXX_Size() int {
	return xxx_messageInfo_VerifierResponse.Size(m)
}
func (m *VerifierResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierResponse proto.InternalMessageInfo

func (m *VerifierResponse) GetVerifier() []byte {
	if m != nil {
		return m.Verifier
	}
	return nil
}

func (m *VerifierResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type AccessKeyResponse struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessKeyResponse) Reset()         { *m = AccessKeyResponse{} }
func (m *AccessKeyResponse) String() string { return proto.CompactTextString(m) }
func (*AccessKeyResponse) ProtoMessage()    {}
func (*AccessKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *AccessKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessKeyResponse.Unmarshal(m, b)
}
func (m *AccessKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessKeyResponse.Marshal(b, m, deterministic)
}
func (m *AccessKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessKeyResponse.Merge(m, src)
}
func (m *AccessKeyResponse) XXX_Size() int {
	return xxx_messageInfo_AccessKeyResponse.Size(m)
}
func (m *AccessKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccessKeyResponse proto.InternalMessageInfo

func (m *AccessKeyResponse) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

type LogoutResponse struct {
	Approved             bool     `protobuf:"varint,1,opt,name=Approved,proto3" json:"Approved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

type RegisterDeviceResponse struct {
	SRPSalt              []byte   `protobuf:"bytes,1,opt,name=SRPSalt,proto3" json:"SRPSalt,omitempty"`
	MUKSalt              []byte   `protobuf:"bytes,2,opt,name=MUKSalt,proto3" json:"MUKSalt,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Firstname            string   `protobuf:"bytes,5,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,6,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	EncPrivateKey        []byte   `protobuf:"bytes,8,opt,name=EncPrivateKey,proto3" json:"EncPrivateKey,omitempty"`
	EncVaultKey          []byte   `protobuf:"bytes,9,opt,name=EncVaultKey,proto3" json:"EncVaultKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceResponse) Reset()         { *m = RegisterDeviceResponse{} }
func (m *RegisterDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceResponse) ProtoMessage()    {}
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *RegisterDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceResponse.Unmarshal(m, b)
}
func (m *RegisterDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceResponse.Marshal(b, m, deterministic)
}
func (m *RegisterDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceResponse.Merge(m, src)
}
func (m *RegisterDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceResponse.Size(m)
}
func (m *RegisterDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceResponse proto.InternalMessageInfo

func (m *RegisterDeviceResponse) GetSRPSalt() []byte {
	if m != nil {
		return m.SRPSalt
	}
	return nil
}

func (m *RegisterDeviceResponse) GetMUKSalt() []byte {
	if m != nil {
		return m.MUKSalt
	}
	return nil
}

func (m *RegisterDeviceResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *RegisterDeviceResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterDeviceResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterDeviceResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *RegisterDeviceResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterDeviceResponse) GetEncPrivateKey() []byte {
	if m != nil {
		return m.EncPrivateKey
	}
	return nil
}

func (m *RegisterDeviceResponse) GetEncVaultKey() []byte {
	if m != nil {
		return m.EncVaultKey
	}
	return nil
}

type AdminsResponse struct {
	Admins               []string `protobuf:"bytes,1,rep,name=Admins,proto3" json:"Admins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminsResponse) Reset()         { *m = AdminsResponse{} }
func (m *AdminsResponse) String() string { return proto.CompactTextString(m) }
func (*AdminsResponse) ProtoMessage()    {}
func (*AdminsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *AdminsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminsResponse.Unmarshal(m, b)
}
func (m *AdminsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminsResponse.Marshal(b, m, deterministic)
}
func (m *AdminsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminsResponse.Merge(m, src)
}
func (m *AdminsResponse) XXX_Size() int {
	return xxx_messageInfo_AdminsResponse.Size(m)
}
func (m *AdminsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminsResponse proto.InternalMessageInfo

func (m *AdminsResponse) GetAdmins() []string {
	if m != nil {
		return m.Admins
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.api.user.RegisterRequest")
	proto.RegisterType((*Empty)(nil), "go.micro.api.user.Empty")
	proto.RegisterType((*VerifierRequest)(nil), "go.micro.api.user.VerifierRequest")
	proto.RegisterType((*VerifierResponse)(nil), "go.micro.api.user.VerifierResponse")
	proto.RegisterType((*AccessKeyResponse)(nil), "go.micro.api.user.AccessKeyResponse")
	proto.RegisterType((*LogoutResponse)(nil), "go.micro.api.user.LogoutResponse")
	proto.RegisterType((*RegisterDeviceResponse)(nil), "go.micro.api.user.RegisterDeviceResponse")
	proto.RegisterType((*AdminsResponse)(nil), "go.micro.api.user.AdminsResponse")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xda, 0x30,
	0x14, 0x4e, 0x02, 0x04, 0x72, 0xe8, 0xe8, 0x6a, 0x6d, 0x28, 0x42, 0xbd, 0x60, 0x5e, 0x2f, 0x98,
	0x34, 0x65, 0xda, 0xf6, 0x04, 0x4c, 0x63, 0x48, 0x6d, 0x27, 0xa1, 0xa0, 0x76, 0xbb, 0x4d, 0x53,
	0x0f, 0x59, 0x82, 0x24, 0xb3, 0x1d, 0xa4, 0xbe, 0xcc, 0xde, 0x69, 0xef, 0xb1, 0x87, 0x98, 0x6c,
	0x13, 0x27, 0x01, 0x1a, 0xb5, 0x37, 0x88, 0xef, 0xfc, 0x9f, 0xef, 0x7c, 0x0e, 0xbc, 0xce, 0x58,
	0x2a, 0xd2, 0x0f, 0x39, 0x27, 0x4c, 0xfd, 0x04, 0x0a, 0xa3, 0xb3, 0x55, 0x1a, 0x6c, 0x68, 0xcc,
	0xd2, 0x20, 0xca, 0x68, 0x20, 0x1d, 0xf8, 0xaf, 0x03, 0xa7, 0x21, 0x59, 0x51, 0x2e, 0x08, 0x0b,
	0xc9, 0xef, 0x9c, 0x70, 0x81, 0x46, 0xd0, 0xbb, 0xe1, 0x84, 0x25, 0xd1, 0x86, 0xf8, 0xf6, 0xd8,
	0x9e, 0x78, 0xa1, 0xc1, 0xe8, 0x1c, 0xbc, 0x6f, 0x94, 0x71, 0xa1, 0x9c, 0x8e, 0x72, 0x96, 0x06,
	0x99, 0x79, 0x1d, 0xed, 0x9c, 0x2d, 0x9d, 0x59, 0x60, 0xf4, 0x0a, 0x3a, 0xb3, 0x4d, 0x44, 0xd7,
	0x7e, 0x5b, 0x39, 0x34, 0x40, 0x43, 0x70, 0xbf, 0x92, 0x2d, 0x8d, 0x89, 0xdf, 0x51, 0xe6, 0x1d,
	0x42, 0x3e, 0x74, 0x97, 0xe1, 0x62, 0x19, 0xad, 0x85, 0xef, 0x8e, 0xed, 0xc9, 0x49, 0x58, 0x40,
	0x34, 0x86, 0xfe, 0x32, 0x5c, 0xdc, 0x12, 0x46, 0x7f, 0x51, 0xc2, 0xfc, 0xae, 0xf2, 0x56, 0x4d,
	0x32, 0xf7, 0xfb, 0xcd, 0x95, 0xca, 0xed, 0xe9, 0xdc, 0x1d, 0x94, 0xd3, 0x2f, 0xf2, 0xbb, 0x35,
	0x8d, 0xaf, 0xc8, 0x83, 0xef, 0x29, 0x5f, 0x69, 0x40, 0x17, 0xf0, 0x62, 0x96, 0xc4, 0x0b, 0x46,
	0xb7, 0x91, 0x20, 0x32, 0x02, 0x54, 0x44, 0xdd, 0x28, 0xfb, 0xcf, 0x92, 0xf8, 0x36, 0xca, 0xd7,
	0x42, 0xc6, 0xf4, 0x75, 0xff, 0x8a, 0x09, 0x77, 0xe5, 0xa6, 0x99, 0x78, 0xc0, 0x31, 0x9c, 0x16,
	0x43, 0x3d, 0x85, 0xdb, 0x92, 0x0b, 0xa7, 0xc6, 0xc5, 0x39, 0x78, 0xd3, 0x38, 0x26, 0x9c, 0xcb,
	0x7e, 0x9a, 0xd6, 0xd2, 0x80, 0xbf, 0xc0, 0xcb, 0xb2, 0x09, 0xcf, 0xd2, 0x84, 0xab, 0x3b, 0x18,
	0x82, 0x6c, 0x35, 0xa0, 0xc1, 0x08, 0x41, 0x5b, 0x51, 0xe3, 0x28, 0xbb, 0xfa, 0x8f, 0x3f, 0xc2,
	0x99, 0x29, 0x68, 0x8a, 0xd4, 0xda, 0xda, 0xfb, 0x6d, 0xdf, 0xc3, 0xe0, 0x3a, 0x5d, 0xa5, 0xb9,
	0xa8, 0x36, 0x9d, 0x66, 0x19, 0x4b, 0xb7, 0xe4, 0x5e, 0x85, 0xf7, 0x42, 0x83, 0xf1, 0x1f, 0x07,
	0x86, 0x85, 0xcc, 0xf4, 0x56, 0x26, 0xad, 0x72, 0x69, 0xbb, 0x7e, 0xe9, 0xca, 0x1d, 0x9d, 0x86,
	0x3b, 0xb6, 0xf6, 0xef, 0x58, 0xe5, 0xb8, 0xdd, 0xa4, 0xdf, 0x4e, 0x93, 0x7e, 0xdd, 0xc7, 0xf4,
	0xdb, 0xad, 0xea, 0xf7, 0x40, 0x33, 0xbd, 0x27, 0x68, 0xc6, 0x3b, 0xd4, 0xcc, 0x04, 0x06, 0xd3,
	0xfb, 0x0d, 0x4d, 0xb8, 0xe1, 0x65, 0x08, 0xae, 0xb6, 0xf8, 0xf6, 0xb8, 0x25, 0xd5, 0xa0, 0xd1,
	0xa7, 0x7f, 0x2d, 0x68, 0xcb, 0x75, 0xd0, 0x25, 0xf4, 0x0a, 0x4a, 0x11, 0x0e, 0x0e, 0x9e, 0x76,
	0xb0, 0xf7, 0xac, 0x47, 0xfe, 0x91, 0x18, 0xad, 0x53, 0x0b, 0xfd, 0x84, 0xfe, 0x9c, 0x08, 0xa3,
	0x91, 0x63, 0xe5, 0xf6, 0x94, 0x3c, 0x7a, 0xdb, 0x18, 0xa3, 0x97, 0xc0, 0x16, 0xfa, 0x01, 0x83,
	0xfa, 0xe1, 0xd1, 0xa3, 0x73, 0x8c, 0xde, 0x35, 0x6c, 0x51, 0x57, 0x0d, 0xb6, 0xd0, 0x02, 0x4e,
	0xe6, 0x44, 0x18, 0x41, 0x36, 0x94, 0xbd, 0x38, 0xe2, 0x39, 0x90, 0x3b, 0xb6, 0xd0, 0x1c, 0x5c,
	0x2d, 0xe9, 0x86, 0x5a, 0x6f, 0x8e, 0x78, 0xea, 0xef, 0x00, 0x5b, 0xe8, 0x12, 0x3c, 0x39, 0x9a,
	0xba, 0xd7, 0x33, 0x6b, 0xd5, 0x45, 0x80, 0xad, 0x3b, 0x57, 0x7d, 0xba, 0x3f, 0xff, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0xd3, 0x6f, 0xd8, 0xd3, 0x05, 0x00, 0x00,
}
