version: '3.3'

services:
  database:
    image: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5

  cron:
    image: jonb377/website:cron

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5

  router:
    image: jonb377/website:router
    build:
      context: ./router-service
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - consul
      - rabbit

  microweb:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=go.micro.api

  web-service:
    image: jonb377/website:web
    build:
      context: ./web-service
    depends_on:
      - consul
      - rabbit

  auth-service:
    image: jonb377/website:auth
    build:
      context: ./auth-service
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://guest:guest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
    depends_on:
      - database
      - consul
      - rabbit
  
  password-manager-service:
    image: jonb377/website:password-manager
    build:
      context: ./password-manager-service
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://guest:guest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
    depends_on:
      - database
      - consul
      - rabbit

  user-service:
    image: jonb377/website:user
    build:
      context: ./user-service
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://guest:guest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
    depends_on:
      - database
      - consul
      - rabbit
