version: '3.1'

consul:
  command: -server -bootstrap -rejoin
  image: progrium/consul:latest
  hostname: "registry"
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

api:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 api
  build: .
  links:
    - consul
  ports:
    - "8080:8080"

proxy:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 proxy
  build: .
  links:
  - consul
  ports:
  - "8081:8081"
web:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  build: .
  links:
  - consul
  ports:
  - "8082:8082"

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - 9546:9546
    environment:
      MICRO_ADDRESS: ":9546"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database
  
  password-manager-service:
    build:
      context: ./password-manager-service
    ports:
      - 9547:9546
    environment:
      MICRO_ADDRESS: ":9546"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  user-service:
    build:
      context: ./user-service
    ports:
      - 9548:9546
    environment:
      MICRO_ADDRESS: ":9546"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - 5432:5432
