version: '3.3'

services:
  database:
    image: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8500:8500"

  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    image: microhq/micro
    command: api --address=:80 
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=go.micro.api
      - MICRO_API_HANDLER=api
    ports:
      - "80:80"

  microweb:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=go.micro.api

  auth-service:
    build:
      context: ./auth-service
    ports:
      - 9546:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://guest:guest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
    depends_on:
      - database
      - consul
      - rabbit
  
  password-manager-service:
    build:
      context: ./password-manager-service
    ports:
      - 9547:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://guest:guest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
    depends_on:
      - database
      - consul
      - rabbit

  user-service:
    build:
      context: ./user-service
    ports:
      - 9548:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://guest:guest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    restart: always
    depends_on:
      - database
      - consul
      - rabbit
