version: '3.1'

services:
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
      - "8500:8500"

  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  microweb:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "80:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=gomicro.api
    links:
      - consul
      - auth-service
      - password-manager-service
      - user-service

  auth-service:
    build:
      context: ./auth-service
    ports:
      - 9546:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://gues:gest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    links:
      - consul
      - rabbit
    depends_on:
      - database
  
  password-manager-service:
    build:
      context: ./password-manager-service
    ports:
      - 9547:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://gues:gest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    links:
      - consul
      - rabbit
    depends_on:
      - database

  user-service:
    build:
      context: ./user-service
    ports:
      - 9548:8080
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      MICRO_BROKER: "rabbitmq"
      MICRO_BROKER_ADDRESS: "amqp://gues:gest@rabbit:5672"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    links:
      - consul
      - rabbit
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - 5432:5432
