// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/storage/storage.proto

package go_micro_api_storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blob struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Date                 int64    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DeletedAt            int64    `protobuf:"varint,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{0}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Blob) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Blob) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Blob) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type SyncRequest struct {
	LastUpdate           int64    `protobuf:"varint,1,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{1}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

type SyncResponse struct {
	Blobs                []*Blob  `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncResponse) Reset()         { *m = SyncResponse{} }
func (m *SyncResponse) String() string { return proto.CompactTextString(m) }
func (*SyncResponse) ProtoMessage()    {}
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{2}
}

func (m *SyncResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncResponse.Unmarshal(m, b)
}
func (m *SyncResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncResponse.Marshal(b, m, deterministic)
}
func (m *SyncResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResponse.Merge(m, src)
}
func (m *SyncResponse) XXX_Size() int {
	return xxx_messageInfo_SyncResponse.Size(m)
}
func (m *SyncResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResponse proto.InternalMessageInfo

func (m *SyncResponse) GetBlobs() []*Blob {
	if m != nil {
		return m.Blobs
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c87989e2875259d4, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Blob)(nil), "go.micro.api.storage.Blob")
	proto.RegisterType((*SyncRequest)(nil), "go.micro.api.storage.SyncRequest")
	proto.RegisterType((*SyncResponse)(nil), "go.micro.api.storage.SyncResponse")
	proto.RegisterType((*Empty)(nil), "go.micro.api.storage.Empty")
}

func init() { proto.RegisterFile("proto/storage/storage.proto", fileDescriptor_c87989e2875259d4) }

var fileDescriptor_c87989e2875259d4 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xbb, 0x4d, 0xda, 0xfe, 0x3b, 0xed, 0xe1, 0xcf, 0xe0, 0x21, 0xb4, 0x22, 0x71, 0x4f,
	0xb9, 0xb8, 0x4a, 0x7d, 0x01, 0x95, 0x16, 0xbc, 0x09, 0x29, 0x5e, 0x85, 0x4d, 0x33, 0x94, 0x40,
	0x92, 0x8d, 0xd9, 0xad, 0xd0, 0xc7, 0xf2, 0x0d, 0x25, 0x93, 0x8a, 0x3d, 0x84, 0x78, 0xf0, 0xb4,
	0xc3, 0x37, 0xbf, 0xfd, 0x98, 0xf9, 0x18, 0x58, 0x56, 0xb5, 0x71, 0xe6, 0xd6, 0x3a, 0x53, 0xeb,
	0x3d, 0x7d, 0xbf, 0x8a, 0x55, 0xbc, 0xd8, 0x1b, 0x55, 0x64, 0xbb, 0xda, 0x28, 0x5d, 0x65, 0xea,
	0xd4, 0x93, 0x6f, 0xe0, 0x3f, 0xe5, 0x26, 0xc1, 0xff, 0xe0, 0x1d, 0xea, 0x2c, 0x10, 0xa1, 0x88,
	0xa6, 0x71, 0x53, 0x22, 0x82, 0x9f, 0x6a, 0x47, 0xc1, 0x30, 0x14, 0x91, 0x17, 0x73, 0x7d, 0xd2,
	0x74, 0xe0, 0x85, 0x22, 0x9a, 0xb3, 0xa6, 0xf1, 0x12, 0xa6, 0x29, 0xe5, 0xe4, 0x28, 0x7d, 0x74,
	0x81, 0xcf, 0xf0, 0x8f, 0x20, 0x6f, 0x60, 0xb6, 0x3d, 0x96, 0xbb, 0x98, 0xde, 0x0f, 0x64, 0x1d,
	0x5e, 0x01, 0xe4, 0xda, 0xba, 0xd7, 0x8a, 0xad, 0x05, 0xd3, 0x67, 0x8a, 0x7c, 0x80, 0x79, 0x8b,
	0xdb, 0xca, 0x94, 0x96, 0xf0, 0x0e, 0x46, 0x49, 0x6e, 0x12, 0x1b, 0x88, 0xd0, 0x8b, 0x66, 0xab,
	0x85, 0xea, 0x5a, 0x42, 0x35, 0x1b, 0xc4, 0x2d, 0x28, 0x27, 0x30, 0xda, 0x14, 0x95, 0x3b, 0xae,
	0x3e, 0x87, 0x30, 0xd9, 0xb6, 0x00, 0xae, 0x61, 0x1c, 0x53, 0xa9, 0x0b, 0xc2, 0x65, 0xb7, 0x03,
	0x7f, 0x59, 0xf4, 0x35, 0xe5, 0x00, 0x37, 0xf0, 0x6f, 0xab, 0x3f, 0x88, 0xf3, 0xea, 0x99, 0xe4,
	0x37, 0x9b, 0x67, 0x80, 0x35, 0xe7, 0xc3, 0x46, 0x7f, 0x19, 0xe8, 0x05, 0xfc, 0x26, 0x2d, 0xbc,
	0xee, 0xc6, 0xce, 0x82, 0x5f, 0xc8, 0x3e, 0xa4, 0x0d, 0x5b, 0x0e, 0x92, 0x31, 0x9f, 0xca, 0xfd,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x66, 0xfa, 0x53, 0x49, 0x02, 0x00, 0x00,
}
