// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/monitor/monitor.proto

package go_micro_api_monitor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Activity struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Route                string   `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Host                 string   `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_40ac1a5f92d2386c, []int{0}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Activity) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Activity) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_40ac1a5f92d2386c, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Activity)(nil), "go.micro.api.monitor.Activity")
	proto.RegisterType((*Empty)(nil), "go.micro.api.monitor.Empty")
}

func init() { proto.RegisterFile("proto/monitor/monitor.proto", fileDescriptor_40ac1a5f92d2386c) }

var fileDescriptor_40ac1a5f92d2386c = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcd, 0xcf, 0xcb, 0x2c, 0xc9, 0x2f, 0x82, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0x91,
	0xf4, 0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xc4, 0x82, 0x4c, 0x3d, 0xa8, 0x9c, 0x92,
	0x0b, 0x17, 0x87, 0x63, 0x72, 0x49, 0x66, 0x59, 0x66, 0x49, 0xa5, 0x10, 0x1f, 0x17, 0x53, 0x66,
	0x81, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x81, 0x90, 0x08, 0x17, 0x6b, 0x51,
	0x7e, 0x69, 0x49, 0xaa, 0x04, 0x13, 0x58, 0x08, 0xc2, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0xc8, 0x2f,
	0x2e, 0x91, 0x60, 0x06, 0x0b, 0x82, 0xd9, 0x4a, 0xec, 0x5c, 0xac, 0xae, 0xb9, 0x05, 0x25, 0x95,
	0x46, 0x51, 0x5c, 0xec, 0xbe, 0x10, 0x93, 0x85, 0xfc, 0xb9, 0xf8, 0xfc, 0xf2, 0x4b, 0x32, 0xd3,
	0x2a, 0xe1, 0xe6, 0xcb, 0xe9, 0x61, 0x73, 0x82, 0x1e, 0x4c, 0x5e, 0x4a, 0x1a, 0xbb, 0x3c, 0xd8,
	0x64, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x3f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x20, 0x4d,
	0xd8, 0xd7, 0xe6, 0x00, 0x00, 0x00,
}
